### ISSUE TITLE
npm library not existing?

### ISSUE THREAD

**Issue by chiwoojo** [SumoLogic/js-logging-sdk#1]
I'm getting

> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/sumologic-logger

when installing from NodeJS. I also tried sumologic-logger-node with no luck. Is this repo up on NPM?

**Comment by ede-n** [comment]
`npm install sumo-logger` works, not the one mentioned in the documentation `npm install sumologic-logger`.

**Comment by billsaysthis** [comment]
Thanks, will get an update out with the change.

**Comment by billsaysthis** [comment]
Pushed v1.0.1 with the required change.
