### ISSUE TITLE
Add error details to onError callback

### ISSUE THREAD

**Issue by clementallen** [SumoLogic/js-logging-sdk#12]
It would be good to get some details on the error passed in the `onError` method.  Perhaps including some of the body and the status code?

**Comment by billsaysthis** [comment]
Marking as enhancement for next iteration. Or pull request if someone wants to add as configurable option ;)

**Comment by billsaysthis** [comment]
Doesn't your PR for the Graphite support also address this issue?

**Comment by clementallen** [comment]
@billsaysthis yes it does, sorry forgot to link to the pr!

Closed in #26

**Comment by billsaysthis** [comment]
Thanks!
