### ISSUE TITLE
Multiple messages sending on same line

### ISSUE THREAD

**Issue by nwilson-sumo** [SumoLogic/js-logging-sdk#14]
When calling the .log() method in rapid succession, it appears that multiple messages can end up on the same line which then confuses Sumo into thinking they're part of the same message.

I believe this line in sumoLogger.js (55):

`body: currentLogs.concat('\n')`

Needs to be:

`body: currentLogs.join('\n')`

Note the difference between concat and join:

**[Concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat):**

> The concat() method is used to merge two or more arrays. This method does not change the existing arrays, but instead returns a new array.

[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)

**[Join](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join):**

> The join() method joins all elements of an array (or an array-like object) into a string and returns this string.

Since we're trying to append a new line char to each item in the array (and not at the end of the entire array) I think it should use join.

Does this sound right, or is there a reason it's currently using concat?

Thanks!

**Comment by billsaysthis** [comment]
Please see the update I posted yesterday, should resolve this issue.

**Comment by nwilson-sumo** [comment]
Ah yep that should do it - Missed that since I got it from NPM. Thank you sir!

**Comment by nwilson-sumo** [comment]
One more question on this - can we publish this latest version to npm?

**Comment by billsaysthis** [comment]
Updated NPM version too, thanks for the reminder.

**Comment by nwilson-sumo** [comment]
Perfect thank you!
