### ISSUE TITLE
sessionKey pre-pending "sumologic.logger.session"

### ISSUE THREAD

**Issue by nwilson-sumo** [SumoLogic/js-logging-sdk#15]
Sorry in advance if this isn't the right place for this - but I was wondering why the session key adds "sumologic.logger.session" to the beginning of every post.

I have my config set up like:

```
// generate guid using Guid Node package
const sessionID = Guid.raw();

// set options for sumo-logger
var sumoLoggerOpts = {
    endpoint: "MY_SOURCE_ENDPOINT",
    interval: 20000, // Send messages in batches every 20 seconds 
    sendErrors: true,
    sessionKey: sessionID
};
```

Now I would expect the session ID to equal whatever guid is generated so the message looks like:

> {"msg":"session started for user: nwilson with session id: 613dd23b-3422-96b7-3942-c2d08f00bbe2","sessionId":"613dd23b-3422-96b7-3942-c2d08f00bbe2","timestamp":"Thu, 22 Feb 2018 00:19:36 GMT","url":""}

Instead, it looks like:

> {"msg":"session started for user: nwilson with session id: 613dd23b-3422-96b7-3942-c2d08f00bbe2","sessionId":"sumologic.logger.session613dd23b-3422-96b7-3942-c2d08f00bbe2","timestamp":"Thu, 22 Feb 2018 00:19:36 GMT","url":""}

I know where to fix it (in sumoLogger.js on line 5, or 28) but I was curious what its purpose is. Thanks!

**Comment by billsaysthis** [comment]
Really just to ensure a unique identifier in the cookie. If you think it's unnecessary I'm open to a change. Especially one that is sent via pull request :)

**Comment by nwilson-sumo** [comment]
Cool, I'll do that then :) Thanks!

**Comment by clementallen** [comment]
I think a prepended unique identifier is good, but should be controlled by the user.  perhaps add it as a property when configuring the instance of the logger and allow the user to set the value?

**Comment by nwilson-sumo** [comment]
I was thinking the same thing - however, the developer already sets the session ID. If they want something pre-pended, they can do it in the configuration options already. Unless there's some reason to have it separated?

**Comment by nwilson-sumo** [comment]
Actually now that I'm re-reading this, @billsaysthis , you said it's for a unique ID on the "cookie". Shouldn't the cookie's ID be a separate thing from the session ID that goes into what's sent to Sumo?

**Comment by billsaysthis** [comment]
Marking as enhancement for next iteration. Or pull request if someone wants to add as configurable option ;)
