### ISSUE TITLE
Logs aren't sending at all (in commit 33ee127)

### ISSUE THREAD

**Issue by nwilson-sumo** [SumoLogic/js-logging-sdk#16]
Ok now that I've upgraded to the latest version :) I realized in commit 33ee127 that the logs are no longer sending to Sumo. Line 58:

`      body: currentLogs.concat('\n')`

Should be using the logsToSend var instead:

`      body: logsToSend.concat('\n')`

Just want to check here to make sure that's what was intended before opening a PR. Thanks!

**Comment by billsaysthis** [comment]
Not sure how this slipped though, will fix now.

**Comment by nwilson-sumo** [comment]
Thanks again :)
