### ISSUE TITLE
"You must also have Node.js/npm installed to use the SDK. "

### ISSUE THREAD

**Issue by bambery** [SumoLogic/js-logging-sdk#2]
What does this line in the readme mean? "You must also have Node.js/npm installed to use the SDK." The readme gives the impression that I do not need node and can run the library through a variety of means, including just in the browser.

**Comment by billsaysthis** [comment]
Sorry for the very late reply... you're correct in saying that not every use case requires Node/npm but just running the demos does so it seems reasonable to list this way.
