### ISSUE TITLE
BUG? request body is array with last item containing '\n'

### ISSUE THREAD

**Issue by clementallen** [SumoLogic/js-logging-sdk#20]
**Description**
The body sent via request to Sumo Logic is an array with the last item being a string containing just `\n`

**Expected**
I'm presuming the contents was intended to be a string with each array item separated by `\n`?
If so `logsToSend.concat('\n')` should be replaced with `logsToSend.join('\n')`

**Code to replicate**
```javascript
const SumoLogger = require('sumo-logger');

const logger = new SumoLogger({
    endpoint: 'https://example.com'
});

logger.log({
    path: 'pathvalue',
    value: 15
});
```

**Body contents**
```
[ '{"sessionId":"d17b3b67-59c3-4a06-9093-1786dc40c3f2","timestamp":"Thu, 01 Mar 2018 16:38:12 GMT","url":"","path":"pathvalue","value":15}', '\n' ]
```

**Comment by clementallen** [comment]
@billsaysthis if this is a bug as I suspect it is, once you confirm I'll make a PR to fix :)

**Comment by billsaysthis** [comment]
Weird, why would `logsToSend.concat('\n')` have that effect?

**Comment by clementallen** [comment]
@billsaysthis because `concat('\n')` is meant to join arrays, so in this case it's appending `\n` as an item in the array.

`join('\n')`  would turn the array into a string separating the values with `\n` which is what I'm expecting was intended?

**Comment by billsaysthis** [comment]
You are correct!
