### ISSUE TITLE
(bug) window.onerror is not setup. setSendError is not properly called

### ISSUE THREAD

**Issue by yanan-wu-crownbet** [SumoLogic/js-logging-sdk#4]
https://github.com/SumoLogic/js-logging-sdk/blob/f02786242edc967d3ab86a6d8d4b2f7ef271045e/src/sumologic.logger.js#L102

Change
setSendError(opts.sendErrors) => setSendError(this, opts.sendErrors)

**Comment by billsaysthis** [comment]
Thanks for the bug report!
