### ISSUE TITLE
Duplicate messages being sent to SumoLogic

### ISSUE THREAD

**Issue by hellomyhomie** [SumoLogic/js-logging-sdk#6]
The observed result is sumo logic collector is really slow.
AND when SLLogger interval is configured to be long enough which is > collector response time,
then duplicated messages will be sent.
Workflow:
Interval 5000 ms -> send logs -> Another interval loop runs -> send logs twice -> ....(many times) -> Collector responds OK -> logs are finally cleared, but too late.

**Comment by billsaysthis** [comment]
@yanan-wu-crownbet  Do you see the duplication if you increase the interval to say one minute?

**Comment by yanan-wu-crownbet** [comment]
@billsaysthis The logic for clearing the logs is flawed. You have to mark logs to be SENDING to avoid next interval to send it again.
My interval is 5000, and I keep seeing at least 2 identical logs, sometimes can be 4.

**Comment by jbutz** [comment]
@yanan-wu-crownbet are you using `sumoLogger.js` or `sumologic.logger.js`/`sumologic.logger.min.js`?

If it is the former I created #8 to fix the issue.

**Comment by clementallen** [comment]
@billsaysthis can this be closed now that #9 has been merged?

**Comment by billsaysthis** [comment]
I believe so, but please feel free to reopen if you still see an issue.
